const variants = [
  {
    id: 'count-up',
    name: 'Count Up',
    status: 'ready',
    category: 'Counter',
    description: 'Counts from zero into a target dashboard metric.',
  },
  {
    id: 'currency-counter',
    name: 'Currency Counter',
    status: 'ready',
    category: 'Finance',
    description: 'Formats animated totals with currency prefixes and separators.',
  },
  {
    id: 'timer-countdown',
    name: 'Timer Countdown',
    status: 'ready',
    category: 'Timer',
    description: 'Counts down time blocks with urgency-focused motion.',
  },
  {
    id: 'digital-clock',
    name: 'Digital Clock',
    status: 'ready',
    category: 'Clock',
    description: 'Scans through clock values before locking to a final time.',
  },
  {
    id: 'percentage-fill',
    name: 'Percentage Fill',
    status: 'ready',
    category: 'Progress',
    description: 'Animates a percentage number and its progress fill together.',
  },
  {
    id: 'radial-gauge',
    name: 'Radial Gauge',
    status: 'ready',
    category: 'Gauge',
    description: 'Draws a circular progress metric around an animated number.',
  },
  {
    id: 'stepper-number',
    name: 'Stepper Number',
    status: 'ready',
    category: 'Control',
    description: 'Animates numeric changes from plus and minus controls.',
  },
  {
    id: 'scroll-counter',
    name: 'Scroll Counter',
    status: 'ready',
    category: 'Scroll',
    description: 'Maps viewport scroll progress into a changing number.',
  },
  {
    id: 'ticker-number',
    name: 'Ticker Number',
    status: 'ready',
    category: 'Ticker',
    description: 'Moves market-style numeric labels across a ticker strip.',
  },
  {
    id: 'slot-machine',
    name: 'Slot Machine',
    status: 'ready',
    category: 'Randomizer',
    description: 'Spins number reels before landing on a result.',
  },
  {
    id: 'split-flap',
    name: 'Split Flap',
    status: 'ready',
    category: 'Board',
    description: 'Flips digits like a mechanical departure board.',
  },
  {
    id: 'particle-number',
    name: 'Particle Number',
    status: 'ready',
    category: 'Particles',
    description: 'Assembles a numeric mark from animated dot particles.',
  },
  {
    id: 'morphing-number',
    name: 'Morphing Number',
    status: 'ready',
    category: 'Morph',
    description: 'Simulates number shape-shifting with blur, scale, and character changes.',
  },
  {
    id: 'neon-flicker',
    name: 'Neon Flicker',
    status: 'ready',
    category: 'Light',
    description: 'Flickers number glow before stabilizing like a neon sign.',
  },
  {
    id: 'matrix-digits',
    name: 'Matrix Digits',
    status: 'ready',
    category: 'Code',
    description: 'Cycles code-like digits before resolving to the target sequence.',
  },
  {
    id: 'pixel-reveal',
    name: 'Pixel Reveal',
    status: 'ready',
    category: 'Pixel',
    description: 'Builds a number from small block pixels.',
  },
  {
    id: 'flip-calendar',
    name: 'Flip Calendar',
    status: 'ready',
    category: 'Flip',
    description: 'Digits flip into place like calendar cards.',
  },
  {
    id: 'glitch-number',
    name: 'Glitch Number',
    status: 'ready',
    category: 'Glitch',
    description: 'Scrambles symbols and digits before settling on the final value.',
  },
  {
    id: 'odometer',
    name: 'Odometer/Rolling',
    status: 'ready',
    category: 'Rolling',
    description: 'Rolls each digit vertically into the final number.',
  },
];

export default variants;
